17 design 친구페이지 레이아웃 수정 및 추가
kakao-tech-campus-2nd-step3/Team22_Android pull request #25
Opened 2024-09-27 10:47 UTC by nJiyeon

## #️⃣연관된 이슈

> #17 

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
- 화면의 레이아웃을 피그마 디자인에 맞게 수정하였습니다.
- 대기 중인 친구 항목을 제외하고 피그마 디자인과 유사하게 디자인을 완료하였습니다.
- 각각의 데이터를 `Adapter`로 연결하여 `RecyclerView`로 띄우도록 수정하였습니다.
- 지난주에 리뷰해주신대로 `ConstraintLayout` 내 `LinearLayout` 배치를 지양하였습니다.

### 스크린샷 (선택)
<img width="326" alt="image" src="https://github.com/user-attachments/assets/bc04378a-361e-489d-abc0-b514ca136c79">
<img width="323" alt="image" src="https://github.com/user-attachments/assets/708a6756-c12e-4567-aed8-a674141fd97b">

## 💬리뷰 요구사항(선택)

- 대기 중인 친구 항목을 가로로 띄우고 싶어서 Horizontal ScrollView도 적용해보고, RecyclerView도 적용해봤는데 계속해서 레이아웃이 깨지는 상황이 발생하고 있습니다.
- 우선 화면을 정상적으로 띄우기 위해 세로로 항목들을 띄웠는데, ExpandableListView를 적용하면서 동시에 가로로 항목을 띄우는 방식을 잘 모르겠습니다.
>

2024-09-27 20:17 UTC, bigstark requested changes
> 대기 중인 친구 항목을 가로로 띄우고 싶어서 Horizontal ScrollView도 적용해보고, RecyclerView도 적용해봤는데 계속해서 레이아웃이 깨지는 상황이 발생하고 있습니다.

레이아웃이 깨지는 현상은 세로로 나온다는 말씀이시겟죠? LinearLayoutManager 에는 orientation 이라는 것이 있어요! xml 에 orientation 을 직접 적용해도 좋고, LinearLayoutManager 를 생성할 떄 아래와 같이 생성해도 괜찮습니다. 

```kotlin
xxx.layoutManager = LinearLayoutManager(context, RecyclerView.HORIZONTAL, false)
```

2024-09-27 20:17 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/search/FriendAdapter.kt
> +        private val declineButton: Button = itemView.findViewById(R.id.friend_decline_button)
p3; 직접 findViewById 를 사용하기 보다는 viewBinding 로 변경해주세요!

2024-09-27 20:17 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/search/FriendAdapter.kt
> +            }
p2; 이부분은 init 시점에 호출해주세요. bind 시점에는 클릭 리스너 등 리스너를 등록하는 것은 안티패턴이에요!

2024-09-27 20:17 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/search/FriendAdapter.kt
> +        notifyDataSetChanged()
p2; notifyDataSetChanged 는 사용하면 안됩니다. 변화를 잘 처리하고 싶다면 RecyclerView.Adapter 를 사용하기보다 [ListAdapter](https://velog.io/@godmin66/ListAdapter-%EC%82%AC%EC%9A%A9%EB%B2%95) 의 사용을 고민해보시는 것이 좋을 것 같습니다.

2024-09-27 20:17 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/search/FriendSearchActivity.kt
> +        expandableListView.setAdapter(pendingFriendsAdapter)
p2; ExpandableListView 의 사용은 지양해주시는 것이 좋을 것 같아요. ListView 자체가 성능이 좋지 않은 편이라서요.

Expandable 한 ViewGroup 이 존재하고, 그 레이아웃 내에 PendingFriend 의 RecyclerView 가 horizontal orientation 으로 존재하면 될 것 같아요!

2024-09-27 20:17 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/search/PendingFriendAdapter.kt
> +        return view
이런 부분의 경험이 좋지 않아요. ListView 에서는 ViewHolder pattern 을 제대로 활용하지 못하거든요 ㅠㅠ

2024-09-28 02:34 UTC, nJiyeon commented on app/src/main/java/com/team22/soundary/feature/search/FriendAdapter.kt
> +            }
`RecyclerView`의 성능과 뷰의 재사용에 영향을 미칠 수 있기 때문에 위와 같은 방식이`Anti-Pattern`이 된다는 것을 확인하였습니다. 중복 처리에 의한 성능 저하를 막기 위해, 리스너 등록이 한 번만 되도록 init 블록 내에 해당 코드를 넣었습니다! 이렇게 수정하는 것이 맞을까요?

2024-09-28 02:35 UTC, nJiyeon commented on app/src/main/java/com/team22/soundary/feature/search/FriendAdapter.kt
> +            }
> p2; 이부분은 init 시점에 호출해주세요. bind 시점에는 클릭 리스너 등 리스너를 등록하는 것은 안티패턴이에요!

`RecyclerView`의 성능과 뷰의 재사용에 영향을 미칠 수 있기 때문에 위와 같은 방식이`Anti-Pattern`이 된다는 것을 확인하였습니다. 중복 처리에 의한 성능 저하를 막기 위해 리스너 등록이 한 번만 되도록 init 블록 내에 해당 코드를 넣고자 하는데, 이렇게 수정하는 것이 맞을까요?

2024-09-28 02:53 UTC, nJiyeon commented on app/src/main/java/com/team22/soundary/feature/search/FriendAdapter.kt
> +            }
> p2; 이부분은 init 시점에 호출해주세요. bind 시점에는 클릭 리스너 등 리스너를 등록하는 것은 안티패턴이에요!

`init 블록`은 클래스가 초기화되는 시점에 한 번만 호출되므로, 스크롤될 때마다 매번 클릭 리스너를 등록하지 않아도 된다는 것을 확인하였습니다!

2024-10-03 01:31 UTC, akuby21 commented
이번주 프로젝트 진행을 위해 제가 임의로 머지하겠습니다!

2024-10-03 01:31 UTC, merged