[4 Week]  feature : 공유화면의 recyclerview들 구현
kakao-tech-campus-2nd-step3/Team22_Android pull request #28
Opened 2024-09-27 12:57 UTC by anyooin

## #️⃣연관된 이슈
#16 

## 📝작업 내용
공유 화면 - 음악 선택 화면(ShareMusicActivity)에 임시 데이터 띄우기, 클릭 이벤트 추가
공유 화면 - 친구 선택 화면(ShareFriendActivity)에 임시 데이터 띄우기
바텀시트(ShareBottomSheet)에 임시 데이터 띄우기
공유 화면 - 친구 선택 화면의 뒤로 가기 버튼 클릭 이벤트
공유 화면 - 친구 선택 화면의 친구+버튼 클릭 이벤트

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)

2024-09-27 20:38 UTC, bigstark requested changes
전반적으로 view binding, list adapter 등을 사용해주신다면 조금 더 깔끔하게 코드가 작성될 수 있을것 같습니다 👍

2024-09-27 20:38 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/share/FriendListAdapter.kt
> +    private val layoutInflater: LayoutInflater
p4; layout inflater 는 굳이 constructor parameter 로 받지 않아도 괜찮아요!

아래와 같이 onCreateViewHolder 시에 parent 가 가지고 있는 context 를 사용하면 됩니다! 
```kotlin
LayoutInflater.from(parent.context)
```

2024-09-27 20:38 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/share/FriendListAdapter.kt
> +) : RecyclerView.Adapter<FriendListAdapter.ViewHolder>() {
p4; 동일한 ViewHolder 가 반복되는 형태는 최대한 ListAdapter 를 사용해주시면 사용하기 오히려 더 편할거에요.

2024-09-27 20:38 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/share/FriendListAdapter.kt
> +    inner class ViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
p2; inner class 는 안티패턴으로 생각해주시는 것이 좋습니다 :)

2024-09-27 20:38 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/share/FriendListAdapter.kt
> +        }
p4; viewBinding 을 사용해주시면 좋을 것 같아요 :)

2024-09-27 20:38 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/share/MusicListAdapter.kt
> +    }
p5; adapter 의 생성자로 받아도 괜찮을 것 같아요.

2024-09-27 20:38 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/share/MusicListAdapter.kt
> +            }
p2; 이러한 부분들 때문에 안티패턴이 됩니다. 외부 참조를 직접 하는 것은 굉장히 좋지 않은 습관이에요! 클릭 리스너는 ViewHolder 에 callback 형태로 받아주시는 것이 좋을 것 같네요.

2024-09-27 20:38 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/share/ShareBottomSheet.kt
> +    }
p5; 사소하지만, 이렇게 사용하면 onCreateView 를 제거할 수 있습니다.

```suggestion
class ShareBottomSheet : BottomSheetDialogFragment(R.layout.bottom_sheet)
```

2024-09-27 20:38 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/share/ShareFriendActivity.kt
> +        val singer: String? = intent.extras?.getString("singer")
music, singer 와 같은 KEY 값들은 companion object 로 따로 관리해주시는 것이 좋아요.
```kotlin
companion object {
    const val KEY_MUSIC = "music"
    const val KEY_SINGER = "singer
}
```

2024-09-29 16:40 UTC, anyooin commented on app/src/main/java/com/team22/soundary/feature/share/FriendListAdapter.kt
> +    private val layoutInflater: LayoutInflater
피드백대로 수정하였습니다! 
[f77a5e6](https://github.com/kakao-tech-campus-2nd-step3/Team22_Android/pull/28/commits/f77a5e69c4bf8b1aa6e3bcd6d650a3e2da4abf71)

2024-09-29 16:43 UTC, anyooin commented on app/src/main/java/com/team22/soundary/feature/share/ShareBottomSheet.kt
> +    }
피드백대로 수정하였습니다! 불필요한 코드를 제거하여 훨씬 깔끔해진 것 같아요! 감사합니다
[0a21203](https://github.com/kakao-tech-campus-2nd-step3/Team22_Android/pull/28/commits/0a21203768d7bc9b11365dbad7f92ea1aed4e5ae)

2024-09-29 16:45 UTC, anyooin commented on app/src/main/java/com/team22/soundary/feature/share/ShareFriendActivity.kt
> +        val singer: String? = intent.extras?.getString("singer")
아직 사용될지 안될지 모르는 임시 값이라서 그냥 작성했었는데, companion object로 관리해두니 추후 변경에도 편리할것 같습니다! 감사합니다!
[e6bea28](https://github.com/kakao-tech-campus-2nd-step3/Team22_Android/pull/28/commits/e6bea28d559ccef8e344a59b9485c2327345a6ba)

2024-09-29 16:48 UTC, anyooin commented on app/src/main/java/com/team22/soundary/feature/share/FriendListAdapter.kt
> +    inner class ViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
지금까지 아무생각없이  recyclerView를 사용할때 inner class를 사용해왔는데, 이번을 기회로 inner class 사용 시, 암묵적인 참조로 인한 메모리 누수가 발생할 수 있다는 것을 알게 되었습니다! 수정완료하였습니다!
[fff99d7](https://github.com/kakao-tech-campus-2nd-step3/Team22_Android/pull/28/commits/fff99d75628ece8fd39089f5376d1696287150ab)

2024-09-29 16:49 UTC, anyooin commented on app/src/main/java/com/team22/soundary/feature/share/MusicListAdapter.kt
> +    }
피드백대로 수정하였습니다!
[fff99d7](https://github.com/kakao-tech-campus-2nd-step3/Team22_Android/pull/28/commits/fff99d75628ece8fd39089f5376d1696287150ab)

2024-09-29 16:56 UTC, anyooin commented on app/src/main/java/com/team22/soundary/feature/share/MusicListAdapter.kt
> +            }
callback 형태가 아직 익숙하지 않아서, 제대로 잘 작성했는지 궁금합니다!
[fff99d7](https://github.com/kakao-tech-campus-2nd-step3/Team22_Android/pull/28/commits/fff99d75628ece8fd39089f5376d1696287150ab)

2024-09-29 16:57 UTC, anyooin commented on app/src/main/java/com/team22/soundary/feature/share/FriendListAdapter.kt
> +        }
viewBinding 적용하였습니다!
[6948942](https://github.com/kakao-tech-campus-2nd-step3/Team22_Android/pull/28/commits/69489422005af7212c35fe4cbe2f49b4f207e226)

2024-09-29 17:00 UTC, anyooin commented on app/src/main/java/com/team22/soundary/feature/share/FriendListAdapter.kt
> +) : RecyclerView.Adapter<FriendListAdapter.ViewHolder>() {
ListAdapter 적용하였습니다! ListAdapter에 대해 잘 몰랐는데, 이번 기회를 통해 DiffUtil을 사용해 데이터 변경에 대해 편리하다는 것을 알게 되었습니다! 감사합니다
[eda685d](https://github.com/kakao-tech-campus-2nd-step3/Team22_Android/pull/28/commits/eda685dd956a1937d5a82a7877abe39fac98eb55)

2024-09-29 17:02 UTC, anyooin commented
상세한 피드백 감사합니다! 덕분에 많이 배웠습니다. 앞으로도 잘 부탁드립니다!
피드백 수정 내용 중 더 수정해야 할 점이 있다면 알려주시면 감사하겠습니다!

2024-09-30 04:28 UTC, akuby21 commented
이번주 프로젝트 진행을 위해 제가 임의로 머지하겠습니다!

2024-09-30 04:28 UTC, merged