[7 Week] 메인화면 api 연결 및 리팩토링
kakao-tech-campus-2nd-step3/Team22_Android pull request #58
Opened 2024-10-25 13:57 UTC by akuby21

## #️⃣연관된 이슈
#45 

## 📝작업 내용
- Retrofit을 활용하여 서버 데이터 받아오기
- 받아온 데이터는 runCatching 활용하여 Result로 래핑, presentation에서 에러 핸들링
- uiState sealed class로 선언하여 각 상황에 맞는 뷰 구성

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)
작업 하다보니 한 PR에 조금 많은 변경들이 있었습니다.. 죄송합니다 ㅠㅠ
1. 에러 핸들링을 Result로 래핑하여 Fragment(Activity)에 위임하여 처리했습니다. 괜찮은 방법일까요? 아니면 해당 클래스에서 처리하는게 좋을까요?
2. sealed class로 로딩, 성공, 실패 등을 나누어 화면을 구성하도록 해보았습니다. 
해당 방법은 서로 배타적인 상황을 그릴때 편리했지만 뷰모델에서 데이터를 다룰때 타입 캐스팅을 해야하는 번거로움이 있었습니다.
올바르게 이해한 것인지 궁금합니다!

2024-10-27 11:36 UTC, bigstark requested changes
이번 한 주도 고생 많으셨습니다 :)

> 1. 에러 핸들링을 Result로 래핑하여 Fragment(Activity)에 위임하여 처리했습니다. 괜찮은 방법일까요? 아니면 해당 클래스에서 처리하는게 좋을까요?

일단 전반적으로 run catching 이 제대로 동작하지는 않을 것으로 보여요. runcatching 을 통해서 Activity 에서 처리해도 좋지만, 화면이 커지면 커질수록 exception 은 굉장히 많아질거에요. 반면에 Activity 에서의 에러화면은 거의 고정적일 경우가 많죠. 그렇기 떄문에 저는 viewModel 에서 한번 가공하여 activity 에서 필요한 정보만 넘겨주는 방식으로 처리하는 것을 조금 더 선호합니다.

> 2. sealed class로 로딩, 성공, 실패 등을 나누어 화면을 구성하도록 해보았습니다.
해당 방법은 서로 배타적인 상황을 그릴때 편리했지만 뷰모델에서 데이터를 다룰때 타입 캐스팅을 해야하는 번거로움이 있었습니다.
올바르게 이해한 것인지 궁금합니다!

저 개인적으로는 BaseUiState, BaseActivity 등과 같은 것들을 선언하는 것을 좋아하지 않는 편이에요. 왜냐하면 화면의 요구사항이 항상 달라지기 때문이에요. UiState 에서도 지금 단순하게는 Success / Fail / Loading 을 두었지만, 특정 화면에서 Init 이나Placeholder, 
 Release 와 같은 단계가 필요하다고 가정한다면 애매해지겠죠. 또한 Error 에 대한 화면이 굉장히 복잡한 화면이 생길수도 있구요. 그래서 저는 각 화면마다 따로 선언해서 사용하는 편이에요. 
다만 이것은 저의 선호도일뿐, UiState 를 공용으로 사용할 수 있는 상황이라면 Loading / Success / Error 로 처리해도 괜찮습니다.

2024-10-27 11:36 UTC, bigstark commented on app/src/main/java/com/team22/soundary/core/UiState.kt
> +}
p3; UiState 가 굳이 data 를 들고있지 않아도 괜찮을 것 같아요. Success 만을 위한 것이니까요..!

```suggestion
sealed class UiState<out T>{
    data object Loading : UiState<Nothing>()
    data class Success<out T>(val data: T) : UiState<T>()
    data class Error(val message: String?) : UiState<Nothing>()
}```

2024-10-27 11:36 UTC, bigstark commented on app/src/main/java/com/team22/soundary/core/data/dto/Dto.kt
> +        SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(this.sharedAt ?: "1980-01-01 00:00:00") ?: Date()
p4; 음 요런거는 매번 파싱하는 로직을 추가하기보다는, Serialization 내에 를 따로 등록해주어 처리하는 편이에요! (Contextual Serialization) 
요 [링크](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#contextual-serialization) 참고해보시면 됩니다.

2024-10-27 11:36 UTC, bigstark commented on app/src/main/java/com/team22/soundary/extensions/DateCalculator.kt
> +    val diff = cur.time - this.time
p2; diff 가 양수인 경우만 고려된 것 같아요. 음수 초가 나올 수 있습니다.

2024-10-27 11:36 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/main/data/ReceivedShareRepositoryImpl.kt
> +                }
p4; failure 처리가 없는데 runCatching 은 제거해도 괜찮지 않을까요?

2024-10-27 11:36 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/main/data/UserRepositoryImpl.kt
> +class UserRepositoryImpl @Inject constructor(
p5; implementation 코드나 module 과 같이 외부에 노출되는지 않아야 하는 것들은 internal 접근제한자를 추가해주면 좋을 것 같아요 :)

2024-10-27 11:36 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/main/domain/GetShareUseCase.kt
> +            }
p2; runCatching 내부에서 throw 하고 있는 것이 onFailure 처리가 없어, 아무런 동작하지 않을 것으로 예상돼요. throw 하는 것이 목적이라면 runCatching  을 제거하는 것이 좋을 것 같습니다.

2024-10-27 11:36 UTC, bigstark commented on app/src/main/java/com/team22/soundary/feature/main/presentation/MainViewModel.kt
> +                }
p3; updateUiState 시에 에러가 발생할 수 있나요? 없다면 runCatching 을 제거해도 될 것 같네요. 만약 share use case 에서 에러를 받기 위함이라면 [catch ](https://developer.android.com/kotlin/flow#exceptions)를 활용해보세요.

2024-10-31 06:30 UTC, akuby21 commented on app/src/main/java/com/team22/soundary/core/UiState.kt
> +}
변경하였습니다! 
제네릭을 처음 다루다보니 미숙했던 점이 있었던거 같습니다..!

2024-10-31 09:39 UTC, akuby21 commented on app/src/main/java/com/team22/soundary/core/data/dto/Dto.kt
> +        SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(this.sharedAt ?: "1980-01-01 00:00:00") ?: Date()
단순하게 직렬화가 힘든 값들은 이런식으로 해결할 수 있네요! 앞으로 유용하게 사용할 것 같습니다 감사합니다!

2024-10-31 09:43 UTC, akuby21 commented on app/src/main/java/com/team22/soundary/extensions/DateCalculator.kt
> +    val diff = cur.time - this.time
간단한 엣지 케이스인데 생각을 못했네요. 바로 수정했습니다!

2024-10-31 09:47 UTC, akuby21 commented on app/src/main/java/com/team22/soundary/feature/main/data/UserRepositoryImpl.kt
> +class UserRepositoryImpl @Inject constructor(
수정했습니다, 이렇게 하면 더욱 모듈간의 분리가 손쉽게 될거 같네요!

2024-10-31 10:08 UTC, akuby21 commented on app/src/main/java/com/team22/soundary/feature/main/data/ReceivedShareRepositoryImpl.kt
> +                }
Result로 래핑하기 위해서 작성했었습니다. 아직 예외처리에 대해서 미숙한 거 같아 이리저리 시도한거 같네요 ㅠㅠ
제거했습니다!

2024-10-31 10:09 UTC, akuby21 commented on app/src/main/java/com/team22/soundary/feature/main/domain/GetShareUseCase.kt
> +            }
runCatching 내부에서 throw할 시, Result.Failure의 형태로 반환되는 것을 보고 이런식으로 작성하였습니다.
아직 예외처리가 미숙한거 같네요.. runCatching 제거하였습니다!

2024-10-31 10:10 UTC, akuby21 commented on app/src/main/java/com/team22/soundary/feature/main/presentation/MainViewModel.kt
> +                }
상위 레이어에서 에러를 throw할 시 Result.Failure의 형태로 내려오기에 에러 핸들링을 위해서 작성했었습니다.
요부분도 제거하였습니다!

2024-10-31 10:11 UTC, akuby21 commented
일정이 겹쳐 이제서야 피드백 반영합니다!
에러 핸들링에 있어서 다소 미숙한 점이 많은거 같습니다.. 일단은 문제되는 runCatching 부분은 전부 제거하였습니다
다음 멘토링때 질문 드리고 이야기 나누고 싶습니다!

2024-10-31 10:13 UTC, akuby21 commented
프로젝트 일정이 촉박하여 부득이하게 제가 머지하겠습니다!
p2에 해당하는 부분은 수정하였고, 추가적인 수정사항이 있으시다면 언제든 말씀주세요!!

2024-10-31 10:13 UTC, merged